language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install git+https://github.com/alexguoxin/InstaPy.git
  - pip install -U pytest
  - pip install numpy
  - pip install matplotlib
# command to run tests
script: pytest
